language: python
python:
 - 2.7
env:
 - BEFORE_DJANGO_VERSION=1.8 TASTYPIE_VERSION="==0.12.2"
 - BEFORE_DJANGO_VERSION=1.8 TASTYPIE_VERSION=">=0.12.2"
 - BEFORE_DJANGO_VERSION=1.9 TASTYPIE_VERSION="==0.12.2"
 - BEFORE_DJANGO_VERSION=1.9 TASTYPIE_VERSION=">=0.12.2"
services: mongodb
install:
 - pip install "Django<$BEFORE_DJANGO_VERSION"
 - pip install "django-tastypie$TASTYPIE_VERSION"
 - pip install pep8
 - pip install pylint
 - python setup.py install
before_script:
 - pep8 django_datastream tests docs
 - pylint django_datastream tests || true
script:
 - python -Wall setup.py test
